name: Matrix GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [21,22]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm code-test



#jobs.<job_id>.strategy.matrix