name: Sequential Bye Action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello GitHub Actions 👋"
  say-bye:
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: Print Hello
        run: echo "Bye GitHub Actions"